name: unison-code-explorer
license: BSD3

# NOTE: StrictData is on.
default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - StrictData
  - TupleSections
  - TypeFamilies
  - TypeOperators

ghc-options: -Wall

dependencies:

  # Notable

  - concur-core
  - concur-replica
  - gitrev
  - servant-server
  - unison-core
  - unison-parser-typechecker
  - wai
  - wai-middleware-static
  - websockets
  - json

  # Other

  - async
  - base
  - bytestring
  - containers
  - directory
  - filepath
  - hashable
  - lens
  - mtl
  - random
  - safe-exceptions
  - stm
  - text
  - time
  - transformers
  - unordered-containers

library:
  source-dirs: src

executables:
  unison-code-explorer:
    source-dirs: .
    main: Main.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - optparse-applicative
      - unison-code-explorer
